[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SirojFlow"
version = "0.1.6"
description = "A lightweight deep learning framework"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name = "Siroj Kafle", email = "sirojkafle0@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy>=1.22.0"
]

[project.urls]
Homepage = "https://github.com/kafleSiroj/SirojFlow.git"